name: Release

on:
  push:
    # run only against tags
    tags:
      - "*"


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages as well 
permissions:
  contents: write
  pages: write
  packages: write
  id-token: write


jobs:
  binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Binaries Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}